#### start

In [2]:
import torch
my_tensor = torch.ones([2,3])
print(my_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### torch判断方法

In [13]:
if torch.cuda.is_available():
    my_tensor = my_tensor.to('cuda')
my_tensor.device

device(type='cuda', index=0)

In [7]:
torch.is_tensor(my_tensor) #张量

True

In [8]:
torch.is_complex(my_tensor) #复数

False

In [9]:
torch.is_floating_point(my_tensor) #浮点数

True

In [11]:
a = torch.ones(1)
torch.is_nonzero(a) #判断标量是否是非零

True

In [12]:
torch.numel(my_tensor) #tensor的个数

6

#### 创建

In [14]:
torch.ones([2,3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.ones_like(my_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [16]:
torch.zeros([2,3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch.zeros_like(my_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [18]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [19]:
torch.arange(0,5,2) #start end step

tensor([0, 2, 4])

In [20]:
torch.range(0,5)

C:\Users\Chaos Lin\AppData\Local\Temp\ipykernel_11784\1393396694.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,5)


tensor([0., 1., 2., 3., 4., 5.])

In [21]:
torch.eye(3) #单位矩阵

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
torch.full([2,2],5)

tensor([[5, 5],
        [5, 5]])

In [23]:
torch.full_like(my_tensor,5)

tensor([[5., 5., 5.],
        [5., 5., 5.]], device='cuda:0')

#### 拼接

In [28]:
b = torch.ones([2,2])
c = torch.zeros([2,3])
torch.cat([b,c],dim=1)
# 要在哪个维度拼接，就要保证除了该维度以外的

tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.]])

In [30]:
torch.chunk(c,chunks=2,dim=1)

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[0.],
         [0.]]))

In [34]:
d =torch.arange(3, 12).view(3, 3)
d

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [36]:
index = torch.tensor([[2, 1, 0]])
e = d.gather(0, index)
e
# 相当于，dim=0那维如index排列，其他维度还是01234的顺序
# 最后取出来的就是[2,0][1,1][0,2]位置的数

tensor([[9, 7, 5]])

In [37]:
a = torch.arange(4)
torch.reshape(a, [2,2])

tensor([[0, 1],
        [2, 3]])

In [38]:
torch.reshape(a,[-1,2])
# -1表示未知数量

tensor([[0, 1],
        [2, 3]])

In [40]:
src = torch.arange(1,11).reshape([2,5])
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [42]:
index = torch.tensor([[0,1,2,0]])
torch.zeros(3,5,dtype=src.dtype).scatter_(0,index,src)
# 类似gather，就是把src的元素按照index和dim来写入目标矩阵
# 有下划线就是原位操作

tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [43]:
a = torch.arange(10).view([5,2])
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [49]:
torch.split(a,[1,4])
# 切分成有多少个元素的数组

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

In [51]:
a = torch.reshape(a, [5,1,2])
a = a.squeeze()
# a = torch.squeeze(a)
a.shape
# 去掉为1的维度
# 也可以指定dim去掉 特定为1的dim


torch.Size([5, 2])

In [64]:
torch.unsqueeze(a,0).shape

torch.Size([1, 5, 2])

In [55]:
b = torch.arange(10,20).view([5,2])
b

tensor([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])

In [56]:
torch.stack([a,b]).shape
# 默认按照dim=0

torch.Size([2, 5, 2])

In [59]:
src =torch.arange(4,10).view([2,3])
torch.take(src, torch.tensor([0,2,5]))
# take相当于把src平铺成一维，然后按index取src的元素


tensor([4, 6, 9])

In [60]:
x = torch.tensor([[1,2],[3,4]])
torch.tile(x,(2,2))
# 复制

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In [61]:
x = torch.arange(4,10).view([2,3])
torch.transpose(x, 0 ,1).shape 
# 交换维度——转置

torch.Size([3, 2])

In [62]:
torch.unbind(torch.arange(1,10).view([3,3]))
# 切片

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [65]:
x= torch.randn(3,2)
y = torch.ones_like(x)
torch.where(x>0,x,y)

tensor([[1.2372, 1.6688],
        [0.4161, 1.0000],
        [0.1000, 1.0000]])

#### 随机种子和函数

In [68]:
torch.normal(mean=0.5 ,std=1.0, size=(1,4))

tensor([[0.7015, 0.4522, 1.3054, 2.1475]])

rand  [0,1)
rand_like
randint
rand_like
randn 正态分布
randperm 随机组合